parameters:
    oro_grid.action.type.redirect.class:    Oro\Bundle\GridBundle\Action\RedirectAction
    oro_grid.action.type.ajax.class:        Oro\Bundle\GridBundle\Action\AjaxAction
    oro_grid.action.type.delete.class:      Oro\Bundle\GridBundle\Action\DeleteAction

services:
    oro_grid.action.type.redirect:
        class: %oro_grid.action.type.redirect.class%
        tags:
            - { name: oro_grid.action.type, alias: oro_grid_action_redirect }

    oro_grid.action.type.ajax:
        class: %oro_grid.action.type.ajax.class%
        tags:
            - { name: oro_grid.action.type, alias: oro_grid_action_ajax }

    oro_grid.action.type.delete:
        class: %oro_grid.action.type.delete.class%
        tags:
            - { name: oro_grid.action.type, alias: oro_grid_action_delete }
