js:
  'grids':
      - '@OroGridBundle/Resources/public/lib/backbone-pageable.js'
      - '@OroGridBundle/Resources/public/lib/backgrid/backgrid.js'
      - '@OroGridBundle/Resources/public/lib/moment/moment.js'
      - '@OroGridBundle/Resources/public/lib/backgrid/extensions/moment-cell/backgrid-moment-cell.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/action/launcher.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/abstractaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/modelaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/navigateaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/deleteaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/refreshcollectionaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/resetcollectionaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/massaction.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/cell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/action/column.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/actionspanel.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/formatter/momentformatter.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/formatter/cellformatter.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/momentcell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/booleancell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/numbercell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/integercell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/stringcell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/htmlcell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/selectcell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/selectrowcell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/cell/selectallheader.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/headercell.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/header.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/row.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/body.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/pagination.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/pagination/input.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/pagesize.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/toolbar.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/filter/list.js'

      - '@OroGridBundle/Resources/public/js/app/loadingmask.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/grid.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/router.js'

      - '@OroGridBundle/Resources/public/js/app/pageablecollection.js'

      - '@OroGridBundle/Resources/public/js/app/datagrid/listener/abstractlistener.js'
      - '@OroGridBundle/Resources/public/js/app/datagrid/listener/columnformlistener.js'

css:
  'grids':
      - 'bundles/orogrid/lib/backgrid/backgrid.css'
      - 'bundles/orogrid/lib/backgrid/extensions/paginator/backgrid-paginator.css'
      - 'bundles/orogrid/lib/multiselect/jquery.multiselect.css'
      - 'bundles/orogrid/lib/multiselect/jquery.multiselect.filter.css'
      - 'bundles/orogrid/css/oro.grid.css'
