oro_entity_config:
    scope:                              datagrid

    entity:
        items:

    field:
        grid_action:
            -                           {"name":"Remove", "route":"oro_entity_extend_field_remove", "filter":"is_extend"}
        layout_action:
            -                           {"name":"Create", "route":"oro_entity_extend_field_create"}
        items:
            enabled:
                grid:
                    type:               boolean
                    label:              'Show in Datagrid'
                    filter_type:        oro_grid_orm_boolean
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               choice
                    options:
                        choices:        ['No', 'Yes']
                        readonly:       true
                        required:       false
                        label:          "Show in Datagrid"


