oro_entity_config:
    scope:                              datagrid

    field:
        grid_action:
            -                           {"name":"Remove", "route":"oro_entityextend_remove", "icon":"trash", "filter":"is_extend"}
        layout_action:
            -                           {"name":"Create", "route":"oro_entityextend_create"}
        items:
            enabled:
                grid:
                    type:               boolean
                    label:              'Show in Datagrid'
                    filter_type:        oro_grid_orm_boolean
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               choice
                    options:
                        choices:        ['No', 'Yes']
                        read_only:       true
                        required:       false
                        label:          "Show in Datagrid"

            is_searchable:
                grid:
                    type:               boolean
                    label:              'Datagrid search'
                    filter_type:        oro_grid_orm_boolean
                    required:           true
                    sortable:           true
                    filterable:         true
                    show_filter:        true
                form:
                    type:               choice
                    options:
                        choices:        ['No', 'Yes']
                        read_only:      false
                        required:       false
                        label:          "Datagrid search"


