config:
    shim:
        'backgrid':
            deps:
                - 'jquery'
                - 'underscore'
                - 'backbone'
            exports: 'Backgrid'

    paths:
        'backbone/pageable-collection': 'bundles/orogrid/lib/backbone-pageable.js'
        'backgrid': 'bundles/orogrid/lib/backgrid/backgrid.js'
        'oro/datagrid/action-launcher': 'bundles/orogrid/js/datagrid/action-launcher.js'
        'oro/datagrid/abstract-action': 'bundles/orogrid/js/datagrid/action/abstract-action.js'
        'oro/datagrid/delete-action': 'bundles/orogrid/js/datagrid/action/delete-action.js'
        'oro/datagrid/ajax-action': 'bundles/orogrid/js/datagrid/action/ajax-action.js'
        'oro/datagrid/mass-action': 'bundles/orogrid/js/datagrid/action/mass-action.js'
        'oro/datagrid/model-action': 'bundles/orogrid/js/datagrid/action/model-action.js'
        'oro/datagrid/navigate-action': 'bundles/orogrid/js/datagrid/action/navigate-action.js'
        'oro/datagrid/refresh-collection-action': 'bundles/orogrid/js/datagrid/action/refresh-collection-action.js'
        'oro/datagrid/reset-collection-action': 'bundles/orogrid/js/datagrid/action/reset-collection-action.js'
        'oro/datagrid/actions-panel': 'bundles/orogrid/js/datagrid/actions-panel.js'
        'oro/datagrid/action-column': 'bundles/orogrid/js/datagrid/column/action-column.js'
        'oro/datagrid/body': 'bundles/orogrid/js/datagrid/body.js'
        'oro/datagrid/action-cell': 'bundles/orogrid/js/datagrid/cell/action-cell.js'
        'oro/datagrid/boolean-cell': 'bundles/orogrid/js/datagrid/cell/boolean-cell.js'
        'oro/datagrid/html-cell': 'bundles/orogrid/js/datagrid/cell/html-cell.js'
        'oro/datagrid/date-cell': 'bundles/orogrid/js/datagrid/cell/date-cell.js'
        'oro/datagrid/datetime-cell': 'bundles/orogrid/js/datagrid/cell/datetime-cell.js'
        'oro/datagrid/number-cell': 'bundles/orogrid/js/datagrid/cell/number-cell.js'
        'oro/datagrid/select-cell': 'bundles/orogrid/js/datagrid/cell/select-cell.js'
        'oro/datagrid/select-row-cell': 'bundles/orogrid/js/datagrid/cell/select-row-cell.js'
        'oro/datagrid/string-cell': 'bundles/orogrid/js/datagrid/cell/string-cell.js'
        'oro/datagrid/filter-list': 'bundles/orogrid/js/datagrid/filter-list.js'
        'oro/datagrid/cell-formatter': 'bundles/orogrid/js/datagrid/formatter/cell-formatter.js'
        'oro/datagrid/datetime-formatter': 'bundles/orogrid/js/datagrid/formatter/datetime-formatter.js'
        'oro/datagrid/number-formatter': 'bundles/orogrid/js/datagrid/formatter/number-formatter.js'
        'oro/datagrid/grid': 'bundles/orogrid/js/datagrid/grid.js'
        'oro/datagrid/header-cell': 'bundles/orogrid/js/datagrid/header-cell/header-cell.js'
        'oro/datagrid/select-all-header-cell': 'bundles/orogrid/js/datagrid/header-cell/select-all-header-cell.js'
        'oro/datagrid/header': 'bundles/orogrid/js/datagrid/header.js'
        'oro/datagrid/abstract-listener': 'bundles/orogrid/js/datagrid/listener/abstract-listener.js'
        'oro/datagrid/column-form-listener': 'bundles/orogrid/js/datagrid/listener/column-form-listener.js'
        'oro/datagrid/callback-listener': 'bundles/orogrid/js/datagrid/listener/callback-listener.js'
        'oro/datagrid/page-size': 'bundles/orogrid/js/datagrid/page-size.js'
        'oro/datagrid/grid-views/view': 'bundles/orogrid/js/datagrid/grid-views/view.js'
        'oro/datagrid/grid-views/model': 'bundles/orogrid/js/datagrid/grid-views/model.js'
        'oro/datagrid/grid-views/collection': 'bundles/orogrid/js/datagrid/grid-views/collection.js'
        'oro/datagrid/pagination-input': 'bundles/orogrid/js/datagrid/pagination-input.js'
        'oro/datagrid/pagination': 'bundles/orogrid/js/datagrid/pagination.js'
        'oro/datagrid/router': 'bundles/orogrid/js/datagrid/router.js'
        'oro/datagrid/row': 'bundles/orogrid/js/datagrid/row.js'
        'oro/datagrid/toolbar': 'bundles/orogrid/js/datagrid/toolbar.js'
        'oro/loading-mask': 'bundles/orogrid/js/loading-mask.js'
        'oro/pageable-collection': 'bundles/orogrid/js/pageable-collection.js'

