parameters:
    oro_grid.datagrid.class:                      Oro\Bundle\GridBundle\Datagrid\Datagrid
    oro_grid.datagrid.parameters.class:           Oro\Bundle\GridBundle\Datagrid\RequestParameters

    oro_grid.orm.query_factory.entity.class:      Oro\Bundle\GridBundle\Datagrid\ORM\QueryFactory\EntityQueryFactory
    oro_grid.orm.query_factory.query.class:       Oro\Bundle\GridBundle\Datagrid\ORM\QueryFactory\QueryFactory

    oro_grid.builder.datagrid.class:              Oro\Bundle\GridBundle\Builder\ORM\DatagridBuilder
    oro_grid.builder.list.class:                  Oro\Bundle\GridBundle\Builder\ListBuilder

    oro_grid.filter.factory.class:                Oro\Bundle\GridBundle\Filter\FilterFactory
    oro_grid.sorter.factory.class:                Oro\Bundle\GridBundle\Sorter\SorterFactory
    oro_grid.action.factory.class:                Oro\Bundle\GridBundle\Action\ActionFactory

    oro_grid.datagrid_manager.registry.class:     Oro\Bundle\GridBundle\Datagrid\DatagridManagerRegistry

    oro_grid.mass_action.dispatcher.class:        Oro\Bundle\GridBundle\Action\MassAction\MassActionDispatcher
    oro_grid.mass_action.parameters_parser.class: Oro\Bundle\GridBundle\Action\MassAction\MassActionParametersParser
    oro_grid.mass_action.handler.delete.class:    Oro\Bundle\GridBundle\Action\MassAction\DeleteMassActionHandler

    oro_grid.route.default_generator.class:       Oro\Bundle\GridBundle\Route\DefaultRouteGenerator

    oro_grid.renderer.class:                      Oro\Bundle\GridBundle\Renderer\GridRenderer
    oro_grid.twig.extension.class:                Oro\Bundle\GridBundle\Twig\GridRendererExtension

services:
    oro_grid.builder.datagrid:
        class:     %oro_grid.builder.datagrid.class%
        arguments:
            - @form.factory
            - @event_dispatcher
            - @oro_security.security_facade
            - @oro_grid.filter.factory
            - @oro_grid.sorter.factory
            - @oro_grid.action.factory
            - %oro_grid.datagrid.class%

    oro_grid.builder.list:
        class:     %oro_grid.builder.list.class%

    oro_grid.filter.factory:
        class:     %oro_grid.filter.factory.class%
        arguments: ["@service_container", ~]

    oro_grid.sorter.factory:
        class:     %oro_grid.sorter.factory.class%
        arguments: ["@service_container"]

    oro_grid.action.factory:
        class:     %oro_grid.action.factory.class%
        arguments: ["@service_container", ~]

    oro_grid.datagrid_manager.registry:
        class:     %oro_grid.datagrid_manager.registry.class%
        arguments: ["@service_container"]

    oro_grid.mass_action.dispatcher:
        class:     %oro_grid.mass_action.dispatcher.class%
        arguments: ["@service_container", "@oro_grid.datagrid_manager.registry"]

    oro_grid.mass_action.parameters_parser:
        class:     %oro_grid.mass_action.parameters_parser.class%

    oro_grid.mass_action.handler.delete:
        class:     %oro_grid.mass_action.handler.delete.class%
        arguments: ["@doctrine.orm.entity_manager", "@translator"]

    oro_grid.renderer:
        class:     %oro_grid.renderer.class%
        arguments: ["@templating.engine.php", "OroGridBundle:Datagrid:list.json.php"]

    oro_grid.twig.extension:
        class:     %oro_grid.twig.extension.class%
        arguments: ["@oro_grid.renderer"]
        tags:
            - { name: twig.extension }
