bazinga_expose_translation:
    name: Frontend translations provided by APY/JsFormValidationBundle and Bazinga/ExposeTranslationBundle
    type: action
    group: ""
    class: Bazinga\ExposeTranslationBundle\Controller\Controller
    method: exposeTranslationAction
