config:
    shim:
        'jquery.bind-first':
            deps:
                - 'jquery'
    paths:
        'jquery.bind-first': 'bundles/orojsformvalidation/lib/jquery.bind-first-0.2.1.js'
        'oro/form-validation': 'bundles/orojsformvalidation/js/form-validation.js'
