parameters:
    oro_jsfv.generator.class: Oro\Bundle\JsFormValidationBundle\Generator\FormValidationScriptGenerator
    oro_jsfv.password_form.validation_listener.class: Oro\Bundle\JsFormValidationBundle\Form\EventListener\EmbedRepeatedFieldListener

services:
    jsfv.generator:
        class: %oro_jsfv.generator.class%
        arguments: [@service_container, @validator.mapping.class_metadata_factory]

    oro_jsfv.password_form.validation_listener:
        class: %oro_jsfv.password_form.validation_listener.class%
        tags:
            - { name: kernel.event_listener, event: jsfv.post_process, method: onJsfvPostProcess }
