oro_titles:
    oro_dataflow_connector_index: DataFlow management
    oro_dataflow_configuration_edit: DataFlow management - Configuration
    oro_dataflow_connector_index: DataFlow management - Connectors
    oro_dataflow_connector_create: DataFlow management - Create connector
    oro_dataflow_connector_edit: DataFlow management - Edit connector
    oro_dataflow_connector_run: DataFlow management - Prepare running

    oro_dataflow_job_create: DataFlow management - Create job
    oro_dataflow_job_edit: DataFlow management - Edit job
