parameters:
#    oro_entity_form.example.class: Oro\Bundle\EntityFormBundle\Example

services:
#    oro_entity_form.example:
#        class: %oro_entity_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
