parameters:
    oro_flexibleentity.value_converter.option.class:  Oro\Bundle\FlexibleEntityBundle\ValueConverter\OptionValueConverter

services:
    oro_flexibleentity.value_converter.date:
        class: %oro_importexport.value_converter.datetime.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_date }

    oro_flexibleentity.value_converter.datetime:
        class: %oro_importexport.value_converter.datetime.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_datetime }

    oro_flexibleentity.value_converter.decimal:
        class: %oro_importexport.value_converter.float.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_decimal }

    oro_flexibleentity.value_converter.integer:
        class: %oro_importexport.value_converter.integer.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_integer }

    oro_flexibleentity.value_converter.text:
        class: %oro_importexport.value_converter.string.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_text }

    oro_flexibleentity.value_converter.varchar:
        class: %oro_importexport.value_converter.string.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_varchar }

    oro_flexibleentity.value_converter.option:
        class: %oro_flexibleentity.value_converter.option.class%
        tags:
            - { name: oro_importexport.value_converter, alias: oro_flexibleentity_option }
