entities_config:
    Oro\Bundle\CustomerBundle\Entity\Customer:
        flexible_manager_class:      Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleEntityManager
        flexible_entity_class:       Oro\Bundle\CustomerBundle\Entity\Customer
        flexible_entity_value_class: Oro\Bundle\CustomerBundle\Entity\CustomerAttributeValue
