parameters:
    customer_manager_class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleEntityManager
    customer_entity_class:  Oro\Bundle\CustomerBundle\Entity\Customer

services:
    customer_manager:
        class:     "%customer_manager_class%"
        arguments: [@service_container, %customer_entity_class%]
