security:
    firewalls:
        main:
            http_basic:
                realm: "Secured test Area"
            provider: oro_user
            form_login: false
            logout: false
            remember_me: false
            anonymous: false
