entities_config:
    Oro\Bundle\ProductBundle\Entity\Product:
        flexible_manager_class:      Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleEntityManager
        flexible_entity_class:       Oro\Bundle\ProductBundle\Entity\Product
        flexible_entity_value_class: Oro\Bundle\ProductBundle\Entity\ProductAttributeValue
        has_translatable_value: true