datagrid:
    demo:
        source:
            type: orm
            query:
                select:
                    - g.id
                    - g.label
                from:
                    - { table: OroCRMContactBundle:Group, alias: g }

        columns:
            label:
                type: field

        properties:
            update_link:
                type: url
                route: orocrm_contact_group_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_contactgroup
                params:
                    - id
