datagrid:
    contactGroup:
        source:
            acl_resource: orocrm_contact_group_view
            type: orm
            query:
                select:
                    - g.id
                    - g.label
                from:
                    - { table: OroCRMContactBundle:Group, alias: g }

        columns:
            label:
                type: field

        properties:
            update_link:
                type: url
                route: orocrm_contact_group_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_contactgroup
                params:
                    - id
        sorters:
            columns:
                label:
                    data_name: g.label

                id:
                    data_name: g.id

            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    adminUsers:
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.firstName
                    - u.lastName
                    - u.created
                from:
                    - { table: OroUserBundle:User, alias: u }

        columns:
            firstName:
                type: field
                frontend_type: string
            lastName:
                type: field
                frontend_type: string
            created:
                type: field
                frontend_type: date

        sorters:
            columns:
                hasRole:
                    data_name: hasRole

                firstName:
                    data_name: u.firstName

            default:
                hasRole: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
                firstName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                created:
                    type: date
                    data_name: u.created

            default:
                created:
                    type: \Oro\Bundle\FilterBundle\Form\Type\Filter\DateRangeFilterType::TYPE_MORE_THAN
                    value:
                        end: 2013-10-07 00:00

    account:
        source:
            type: orm
            query:
                select:
                    - a.id
                    - defaultContact.firstName as contactFirstName
                    - defaultContact.lastName as contactLastName
                    - defaultContactEmail.email as contactEmail
                    - defaultContactPhone.phone as contactPhone
                    - CONCAT(accountOwner.firstName, CONCAT(' ', accountOwner.lastName)) as ownerName
                from:
                    - { table: OroCRMAccountBundle:Account, alias: a }

                join:
                    left:
                        - { join: a.defaultContact, alias: defaultContact }
                        - { join: defaultContact.emails, alias: defaultContactEmail, conditionType: 'WITH', condition: 'defaultContactEmail.primary = true' }
                        - { join: defaultContact.phones, alias: defaultContactPhone, conditionType: 'WITH', condition: 'defaultContactPhone.primary = true' }
                        - { join: a.owner, alias: accountOwner }
        columns:
            name:
                type: field
                label: 'Name'

            contactFirstName:
                type: field
                label: 'Default contact first name'

            contactLastName:
                type: field
                label: 'Default contact last name'

            contactPhone:
                type: field
                label: 'Default contact phone'

            contactEmail:
                type: field
                label: 'Default contact email'

            ownerName:
                type: field
                label: 'Owner'

        flexible_attributes:
            employees:
                filterable: true
        flexible_entity: %orocrm_account.account.entity.class%

        filters:
            default:
                employees:
                    type: 1
                    value: 3
