datagrid:
    contactGroup:
        source:
            acl_resource: orocrm_contact_group_view
            type: orm
            query:
                select:
                    - g.id
                    - g.label
                from:
                    - { table: OroCRMContactBundle:Group, alias: g }

        columns:
            label:
                type: field

        properties:
            update_link:
                type: url
                route: orocrm_contact_group_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_contactgroup
                params:
                    - id
        sorters:
            columns:
                label:
                    data_name: g.label

                id:
                    data_name: g.id

            default:
                label: %oro_grid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                label:
                    type: string
                    data_name: g.label

    adminUsers:
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.firstName
                    - u.lastName
                    - u.username
                    - u.email
                from:
                    - { table: OroUserBundle:User, alias: u }

        sorters:
            columns:
                hasRole:
                    data_name: hasRole

                firstName:
                    data_name: u.firstName

            default:
                hasRole: %oro_grid.extension.orm_sorter.class%::DIRECTION_DESC
                firstName: %oro_grid.extension.orm_sorter.class%::DIRECTION_ASC
