oro_menu_config:
    items:
        grid_demo_tab:
            label: 'Demo grids'
            uri: '#'
            extras:
                position: 60

        grid_contactGroup:
            label: 'Contact group'
            route: 'oro_demo_index'
            routeParameters:
                gridName: contactGroup

        grid_account:
            label: 'Flexible account'
            route: 'oro_demo_index'
            routeParameters:
                gridName: account

        grid_adminUsers:
            label: 'Admin role users'
            route: 'oro_demo_admin_users'

    tree:
        application_menu:
            children:
                grid_demo_tab:
                    children:
                        grid_contactGroup: ~
                        grid_adminUsers:   ~
                        grid_account:      ~
