parameters:
    oro_demo.event_listener.admin_role_users.class: Oro\Bundle\DemoBundle\EventListener\AdminRoleUsersGrid

services:
    oro_demo.event_listener.admin_role_users:
        class: %oro_demo.event_listener.admin_role_users.class%
        arguments:
          - @service_container
        tags:
          - { name: kernel.event_listener, event: oro_grid.datgrid.build.after.adminUsers, method: onBuildAfter }
