parameters:
    oro_datamodel.locale_helper.class: Oro\Bundle\DataModelBundle\Helper\LocaleHelper
    
services:

    # provide some utility methods to manage locale (TODO should be move in "core")
    oro_datamodel.locale_helper:
        class:        "%oro_datamodel.locale_helper.class%"
        arguments:    [%locale%, @service_container]

    # deal with translatable behaviour
    oro_datamodel.translatable_listener:
        class: Oro\Bundle\DataModelBundle\Listener\TranslatableListener
        calls:
            - [ setLocaleHelper, [ @oro_datamodel.locale_helper ] ]
        tags:
            - { name: doctrine.event_subscriber }

    # deal with timestampable behaviour
    oro_datamodel.timestampable_listener:
        class: Oro\Bundle\DataModelBundle\Listener\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber }

    # deal with hasValueRequired behaviour
    oro_datamodel.has_required_value_listener:
        class: Oro\Bundle\DataModelBundle\Listener\HasRequiredValueListener
        tags:
            - { name: doctrine.event_subscriber }
