parameters:
    pim_localization.factory.date.class: Pim\Component\Localization\Factory\DateFactory
    pim_localization.factory.number.class: Pim\Component\Localization\Factory\NumberFactory

    pim_localization.factory.date.formats:
        en: 'MM/dd/yyyy'
        en_US: 'MM/dd/yyyy'
        fr: 'dd/MM/yyyy'
        fr_FR: 'dd/MM/yyyy'
    pim_localization.factory.datetime.formats:
        en: 'MM/dd/yyyy hh:mm'
        en_US: 'MM/dd/yyyy hh:mm'
        fr: 'dd/MM/yyyy hh:mm'
        fr_FR: 'dd/MM/yyyy hh:mm'
    pim_localization.factory.number.currency_formats:
        en_US: '¤#,##0.00'
        fr_FR: '#,##0.00 ¤'

services:
    pim_localization.factory.currency:
        class: %pim_localization.factory.number.class%
        arguments:
            - %pim_localization.factory.number.currency_formats%

    pim_localization.factory.number:
        class: %pim_localization.factory.number.class%
        arguments:
            - []

    pim_localization.factory.date:
        class: %pim_localization.factory.date.class%
        arguments:
            - %pim_localization.factory.date.formats%

    pim_localization.factory.datetime:
        class: %pim_localization.factory.date.class%
        arguments:
            - %pim_localization.factory.datetime.formats%
