parameters:
    pim_localization.presenter.prices.class: Pim\Component\Localization\Presenter\PricesPresenter

services:
    pim_localization.presenter.prices:
        class: %pim_localization.presenter.prices.class%
        arguments:
            - '@pim_localization.factory.number'
